#!/bin/bash
# Local Agent Society — installer
# Usage: ./install.sh [AgentName]
# Default agent name: System
set -e

INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FAMILY="${1:-System}"

echo "Local Agent Society — installing"
echo "  Directory : $INSTALL_DIR"
echo "  Agent     : $FAMILY"
echo ""

# ── 1. Build the Electron widget app bundle ───────────────────────────────────
# (Replaces the old Swift tray.swift build — see swift-widget-final git tag
# for the retired native implementation.)
echo "[ 1/5 ] Building Electron widget..."
ELECTRON_DIR="$INSTALL_DIR/widget-electron"
(cd "$ELECTRON_DIR" && npm install --no-audit --no-fund -q && npm run build -q)
ELECTRON_APP="$ELECTRON_DIR/dist/mac-arm64/Local Agent Society.app"
if [ ! -d "$ELECTRON_APP" ]; then
    # Intel build output path differs from Apple Silicon's.
    ELECTRON_APP="$ELECTRON_DIR/dist/mac/Local Agent Society.app"
fi
if [ -d "$ELECTRON_APP" ]; then
    echo "         built: $ELECTRON_APP"
else
    echo "         ⚠️  Electron widget build did not produce an .app bundle — check widget-electron/dist"
fi

# ── 2. Python dependencies ────────────────────────────────────────────────────
echo "[ 2/5 ] Installing Python dependencies..."
VENV="$INSTALL_DIR/backend/.venv"
python3 -m venv "$VENV"
"$VENV/bin/pip" install -q fastapi "uvicorn[standard]"

# ── 3. Install skills ─────────────────────────────────────────────────────────
echo "[ 3/5 ] Installing skills..."
for skill in local-agent-voice local-agent-pronunciation local-agent-widget; do
    mkdir -p ~/.claude/skills/$skill
    sed "s|INSTALL_DIR|$INSTALL_DIR|g" \
        "$INSTALL_DIR/skills/$skill/SKILL.md" \
        > ~/.claude/skills/$skill/SKILL.md
    echo "         skill: $skill"
done

# las-agent lives under .claude/skills (project-tracked) instead of skills/,
# since it doubles as this repo's own Claude Code skill.
mkdir -p ~/.claude/skills/las-agent
cp "$INSTALL_DIR/.claude/skills/las-agent/SKILL.md" ~/.claude/skills/las-agent/SKILL.md
echo "         skill: las-agent"

# ── 4. Update ~/.claude/settings.json ────────────────────────────────────────
# No Stop hook here anymore — the old one just spoke a fixed "Here! <Family>"
# with no real content. Reporting is now the las-agent skill's job: it
# instructs the model to speak an actual closing summary of what it did via
# `las speak`, so removing any stale Stop-hook entry from a previous install
# is part of this step too.
echo "[ 4/5 ] Updating Claude settings..."
python3 - <<PYEOF
import json, os

path = os.path.expanduser("~/.claude/settings.json")
with open(path) as f:
    s = json.load(f)

# permissions
perms = s.setdefault("permissions", {}).setdefault("allow", [])
for p in ["Bash(curl:*)", "Bash(python3:*)", "Bash(nohup:*)"]:
    if p not in perms:
        perms.append(p)

# Remove any leftover announce-here.sh Stop hook from a previous install.
stop = s.get("hooks", {}).get("Stop", [])
for entry in stop:
    entry["hooks"] = [h for h in entry.get("hooks", []) if "announce-here.sh" not in h.get("command", "")]
s.setdefault("hooks", {})["Stop"] = [e for e in stop if e.get("hooks")]
if not s["hooks"]["Stop"]:
    del s["hooks"]["Stop"]

with open(path, "w") as f:
    json.dump(s, f, indent=2)
print("         settings.json updated")
PYEOF

rm -f ~/.claude/hooks/announce-here.sh

# ── Initialize backend data ───────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR/backend/data"
for f in registry.json ports.json; do
    [ ! -f "$INSTALL_DIR/backend/data/$f" ] && echo '{}' > "$INSTALL_DIR/backend/data/$f"
done
[ ! -f "$INSTALL_DIR/backend/data/queue.json" ] && echo '[]' > "$INSTALL_DIR/backend/data/queue.json"
[ ! -f "$INSTALL_DIR/backend/data/attribution.json" ] && echo '[]' > "$INSTALL_DIR/backend/data/attribution.json"

# ── Purge legacy per-project watcher plists (haiku / opus) ───────────────────
# These were generated by an old multi-model system (pre-TTY-injection era).
# The scripts they referenced no longer exist; remove any survivors.
echo "[ +0 ] Purging legacy watcher plists..."
LEGACY=$(ls ~/Library/LaunchAgents/*.haiku.plist ~/Library/LaunchAgents/*.opus.plist 2>/dev/null || true)
if [ -n "$LEGACY" ]; then
    for plist in $LEGACY; do
        launchctl unload "$plist" 2>/dev/null || true
        rm -f "$plist"
        echo "         removed $(basename "$plist")"
    done
else
    echo "         none found"
fi

# ── Purge legacy new-local-agent skill ────────────────────────────────────────
# Registration is now covered by `las agent new` alone; the skill duplicated
# that flow by hand (curl/python3) instead of calling the CLI.
if [ -d ~/.claude/skills/new-local-agent ]; then
    rm -rf ~/.claude/skills/new-local-agent
    echo "         removed legacy new-local-agent skill"
fi

# ── Register launchd agent (backend) ─────────────────────────────────────────
PLIST=~/Library/LaunchAgents/com.localagent.system.plist
cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.localagent.system</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$INSTALL_DIR/backend/serve.sh</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>$INSTALL_DIR/backend/launchd.log</string>
    <key>StandardErrorPath</key><string>$INSTALL_DIR/backend/launchd.log</string>
</dict>
</plist>
PLIST
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"

# ── Create .agent.json if not present ────────────────────────────────────────
if [ ! -f "$INSTALL_DIR/.agent.json" ]; then
    TODAY=$(date '+%Y-%m-%d')
    cat > "$INSTALL_DIR/.agent.json" <<JSON
{
  "name": "$FAMILY",
  "voice": "Samantha",
  "pronunciation": "$FAMILY",
  "backend_url": "http://localhost:8700",
  "frontend_url": "http://localhost:8700/widget/$FAMILY",
  "created": "$TODAY",
  "report_max_chars": 40
}
JSON
fi

# ── Install `las` CLI ─────────────────────────────────────────────────────────
echo "[ +1 ] Installing las CLI..."
if command -v pipx &>/dev/null; then
    pipx install -e "$INSTALL_DIR" --force -q
    # Ensure ~/.local/bin is in PATH for future shells
    pipx ensurepath --force -q 2>/dev/null || true
    echo "         las → installed via pipx"
else
    pip3 install -e "$INSTALL_DIR" -q --break-system-packages 2>/dev/null \
        || pip3 install -e "$INSTALL_DIR" -q
    echo "         las → installed via pip"
fi

# ── Verify `las` is reachable — symlink into a PATH dir only if needed ────────
# pip+Homebrew installs directly to /opt/homebrew/bin; pipx installs to ~/.local/bin.
# Only create a symlink when las lives outside the standard PATH directories.
LAS_BIN="$HOME/.local/bin/las"
if [ -f "$LAS_BIN" ]; then
    for TARGET_DIR in /opt/homebrew/bin /usr/local/bin; do
        DEST="$TARGET_DIR/las"
        if [ -d "$TARGET_DIR" ] && [ -w "$TARGET_DIR" ] && [ "$LAS_BIN" != "$DEST" ]; then
            ln -sf "$LAS_BIN" "$DEST" 2>/dev/null \
                && echo "         las → symlinked to $DEST" \
                && break
        fi
    done
fi

# Warn only if las is genuinely unreachable
if ! command -v las &>/dev/null \
   && [ ! -f "/opt/homebrew/bin/las" ] \
   && [ ! -f "/usr/local/bin/las" ]; then
    echo ""
    echo "  ⚠️  'las' not found in PATH. Add this to ~/.zshrc and reopen your terminal:"
    echo "       export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

echo ""
echo "Done! Start with:"
echo "  las start"
echo "  las status"
